function createobject
%CREATEOBJECT

%  Auto-generated by MATLAB on 29-Apr-2016 17:07:26

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

t=tasadofi();
disp(t);