function createobject1
%CREATEOBJECT1

%  Auto-generated by MATLAB on 03-May-2016 10:30:09

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information

% uicontrol(...);

